### ISSUE TITLE
Añadir los componentes para la parte principal del cliente, Formulario de Tweets y Tarjeta de los tweets, ademas de sus funcion de favorito, editar y eliminar

### ISSUE THREAD

**Issue by AnggeloHuz** [maikolguerrero/socialtweet-client#2]

**Comment by maikolguerrero** [comment]
# Revisadas las nuevas funcionalidades

## Agregar Tweet
![Image](https://github.com/maikolguerrero/socialtweet-client/assets/117484381/566548da-8870-4b47-9792-03c70cfe6b60)

![Image](https://github.com/maikolguerrero/socialtweet-client/assets/117484381/36a956fc-f1ac-410b-b64c-c58419b5f411)

## Editar Tweet
![Image](https://github.com/maikolguerrero/socialtweet-client/assets/117484381/df8b0d9c-4a19-42d2-a33d-1dc35e23d20b)

![Image](https://github.com/maikolguerrero/socialtweet-client/assets/117484381/aec72442-3085-4270-82d2-3482355340d9)

## Agregar Favorito
![Image](https://github.com/maikolguerrero/socialtweet-client/assets/117484381/acd1160b-7ede-4c13-a577-06dcc4af7254)

## Eliminar Tweet
![Image](https://github.com/maikolguerrero/socialtweet-client/assets/117484381/875e0fa2-6040-4f4a-856f-c2fc8b4052dd)
